package reporting

import (
	"bytes"
	"fmt"
	"sort"
)

// RenderMarkdown produces the human-readable report: verdict headline,
// axis scores, gate status, evidence-backed gaps, and the lite prep pack.
func RenderMarkdown(r *Report) []byte {
	var b bytes.Buffer

	fmt.Fprintf(&b, "# JD Fit Report — %s\n\n", r.Job.Title)
	fmt.Fprintf(&b, "**Verdict: %s** · score %.0f/100\n\n", r.Verdict, r.Score*100)
	fmt.Fprintf(&b, "- Job: %s @ %s (%s)\n", r.Job.Title, r.Job.Company, r.Job.Location)
	fmt.Fprintf(&b, "- Source: `%s` %s\n", r.Job.Source, r.Job.URL)
	fmt.Fprintf(&b, "- Profile: `%s` · CV: `%s`\n\n", r.Profile, r.CV)

	b.WriteString("## Rubric\n\n")
	b.WriteString("| Axis | Score |\n|---|---|\n")
	axes := make([]string, 0, len(r.Axes))
	for name := range r.Axes {
		axes = append(axes, name)
	}
	sort.Strings(axes)
	for _, name := range axes {
		fmt.Fprintf(&b, "| %s | %.0f/100 |\n", name, r.Axes[name]*100)
	}
	b.WriteString("\n## Gates\n\n")
	for _, g := range r.Gates {
		status := "✅"
		if !g.Passed {
			status = "⛔"
		}
		fmt.Fprintf(&b, "- %s `%s` — %s\n", status, g.Name, g.Reason)
		if g.JDEvidence != "" {
			fmt.Fprintf(&b, "  JD: %s\n", g.JDEvidence)
		}
	}
	b.WriteString("\n## Gaps\n\n")
	if len(r.Gaps) == 0 {
		b.WriteString("No gaps found.\n")
	} else {
		for i, g := range r.Gaps {
			fmt.Fprintf(&b, "%d. **%s** (impact: `%s`)\n", i+1, g.Requirement, g.Impact)
			fmt.Fprintf(&b, "   - JD: %s\n   - CV: %s\n   - Action: `%s`\n", g.JDEvidence, g.CVEvidence, g.Action)
		}
	}

	b.WriteString("\n## Prep Pack\n\n")
	b.WriteString("### Interview questions\n")
	for _, q := range r.Prep.Questions {
		fmt.Fprintf(&b, "- %s\n", q)
	}
	b.WriteString("\n### References\n")
	for _, ref := range r.Prep.References {
		fmt.Fprintf(&b, "- [%s](%s) — %s\n", ref.Title, ref.URL, ref.Source)
	}
	b.WriteString("\n### Next actions\n")
	for _, a := range r.Prep.NextActions {
		fmt.Fprintf(&b, "- [ ] %s\n", a)
	}
	b.WriteString("\n---\n*Generated by jdctl · schema " + SchemaVersion + "*\n")
	return b.Bytes()
}
